eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: localhost
#    nonSecurePort: 80
